---
  
- name: Ensure VMDK SC is present
  k8s:
    state: present
    kind: StorageClass
    api_version: storage.k8s.io/v1
    name: vmdk
    merge_type:
      - strategic-merge
      - merge
    definition:
      provisioner: kubernetes.io/vsphere-volume
      reclaimPolicy: Retain
      volumeBindingMode: Immediate
      parameters:
        datastore: vm_openshift
        diskformat: thin

- name: Ensure NFS SC is present
  k8s:
    state: present
    kind: StorageClass
    api_version: storage.k8s.io/v1
    name: nfs
    merge_type:
      - strategic-merge
      - merge
    definition:
      provisioner: kubernetes.io/no-provisioner
      reclaimPolicy: Retain
      volumeBindingMode: Immediate

- name: Ensure PV for etcd backups is present
  k8s:
    state: present
    kind: PersistentVolume
    api_version: v1
    name: etcd-backups
    merge_type:
      - strategic-merge
      - merge
    definition:
      spec:
        accessModes:
          - ReadWriteMany
        capacity:
          storage: '{{ etcd_nfs_size }}'
        nfs:
          path: '{{ etcd_nfs_path }}'
          server: '{{ etcd_nfs_server }}'
        persistentVolumeReclaimPolicy: Retain
        storageClassName: nfs
        volumeMode: Filesystem

- name: Ensure PV for image registry is present
  k8s:
    state: present
    kind: PersistentVolume
    api_version: v1
    name: image-registry
    merge_type:
      - strategic-merge
      - merge
    definition:
      spec:
        accessModes:
          - ReadWriteMany
        capacity:
          storage: '{{ registry_nfs_size }}'
        nfs:
          path: '{{ registry_nfs_path }}'
          server: '{{ registry_nfs_server }}'
        persistentVolumeReclaimPolicy: Retain
        storageClassName: nfs
        volumeMode: Filesystem
