---
- name: Configure Monitoring and Move Monitoring to Infra nodes
  k8s:
    api_version: v1
    state: present
    kind: ConfigMap
    name: cluster-monitoring-config
    namespace: openshift-monitoring
    merge_type:
      - strategic-merge
      - merge
    definition:
      data:
        config.yaml: |+
          enableUserWorkload: true
          alertmanagerMain:
            volumeClaimTemplate:
              spec:
                storageClassName: thin
                volumeMode: Filesystem
                resources:
                  requests:
                    storage: 40Gi
            nodeSelector:
              node-role.kubernetes.io/infra: ""
            tolerations:
            - key: infra
              value: reserved
              effect: NoSchedule
            - key: infra
              value: reserved
              effect: NoExecute
          prometheusK8s:
            retention: 12h
            volumeClaimTemplate:
              spec:
                storageClassName: thin
                volumeMode: Filesystem
                resources:
                  requests:
                    storage: 40Gi
            nodeSelector:
              node-role.kubernetes.io/infra: ""
            tolerations:
            - key: infra
              value: reserved
              effect: NoSchedule
            - key: infra
              value: reserved
              effect: NoExecute
          prometheusOperator:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
            tolerations:
            - key: infra
              value: reserved
              effect: NoSchedule
            - key: infra
              value: reserved
              effect: NoExecute
          grafana:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
            tolerations:
            - key: infra
              value: reserved
              effect: NoSchedule
            - key: infra
              value: reserved
              effect: NoExecute
          k8sPrometheusAdapter:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
            tolerations:
            - key: infra
              value: reserved
              effect: NoSchedule
            - key: infra
              value: reserved
              effect: NoExecute
          kubeStateMetrics:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
            tolerations:
            - key: infra
              value: reserved
              effect: NoSchedule
            - key: infra
              value: reserved
              effect: NoExecute
          telemeterClient:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
            tolerations:
            - key: infra
              value: reserved
              effect: NoSchedule
            - key: infra
              value: reserved
              effect: NoExecute
          openshiftStateMetrics:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
            tolerations:
            - key: infra
              value: reserved
              effect: NoSchedule
            - key: infra
              value: reserved
              effect: NoExecute
          thanosQuerier:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
            tolerations:
            - key: infra
              value: reserved
              effect: NoSchedule
            - key: infra
              value: reserved
              effect: NoExecute
