---
- name: Create AD service account secret
  k8s:
    state: present
    kind: Secret
    name: ad-secret
    namespace: openshift-config
    merge_type:
      - strategic-merge
      - merge
    definition:
      data:
        bindPassword: "{{ ad_password | b64encode }}"
 
- name: Setup Identity Provider
  k8s:
    api_version: config.openshift.io/v1
    kind: OAuth
    merge_type:
      - strategic-merge
      - merge
    definition:
      metadata:
       name: cluster
      spec:
       identityProviders:
         - ldap:
             attributes:
               email: []
               id:
               - sAMAccountName
               name:
               - displayName
               preferredUsername:
               - sAMAccountName
             bindDN: "{{ad_username}}"
             bindPassword:
               name: ad-secret
             insecure: true
             url: "{{ad_server_url}}/{{ad_user_search_dn}}?sAMAccountName?sub?"
           mappingMethod: claim
           name: ldap
           type: LDAP
 
 
- name: Create Service Account
  k8s:
    state: present
    kind: ServiceAccount
    namespace: openshift-config
    name: ad-sync
 
- name: Bind cluster-admin role to the ad-sync Service Account
  k8s:
    state: present
    api_version: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    name: cluster-admin-ad-sync-sa-crb
    merge_type:
      - strategic-merge
      - merge
    definition:
      metadata:
        annotations:
          rbac.authorization.kubernetes.io/autoupdate: "true"
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
      - kind: ServiceAccount
        name: ad-sync
        namespace: openshift-config
 
- name: Create ConfigMap for AD sync
  k8s:
    state: present
    kind: ConfigMap
    api_version: v1
    name: ad-sync
    namespace: openshift-config
    merge_type:
      - strategic-merge
      - merge    
    definition:
      data:
        ad-sync.sh: >-
          #!/bin/sh
     
          oc adm groups sync --sync-config=/ad-sync/ad-sync.yaml
          --whitelist=/ad-sync/whitelist.yaml --confirm; echo "Above AD Groups were
          synced with OCP"
        ad-sync.yaml: |
          kind: LDAPSyncConfig
          apiVersion: v1
          url: "{{ ad_server_url }}"
          insecure: true
          bindDN: "{{ ad_username }}"
          bindPassword: "{{ ad_password }}"
          augmentedActiveDirectory:
              groupsQuery:
                  baseDN: "{{ ad_group_search_dn }}"
                  derefAliases: never
                  pageSize: 0
              groupUIDAttribute: dn
              groupNameAttributes: [ cn ]
              usersQuery:
                  baseDN: "{{ ad_user_search_dn }}"
                  scope: sub
                  filter: (objectclass=organizationalPerson)
                  derefAliases: never
                  pageSize: 0
              userNameAttributes: [ sAMAccountName ]
              groupMembershipAttributes: [ "memberOf:1.2.840.113556.1.4.1941:" ]
        whitelist.yaml: |
          CN={{ ad_admin_group }},{{ ad_group_search_dn }}
          CN={{ ad_basic_user_group }},{{ ad_group_search_dn }}
          CN={{ ad_cluster_admin_group }},{{ ad_group_search_dn }}
          CN={{ ad_cluster_status_group }},{{ ad_group_search_dn }}
          CN={{ ad_edit_group }},{{ ad_group_search_dn }}
          CN={{ ad_self_provisioner_group }},{{ ad_group_search_dn }}
          CN={{ ad_view_group }},{{ ad_group_search_dn }}
 
- name: Get cli image with tag
  k8s_info:
    api_version: image.openshift.io/v1
    kind: ImageStream
    name: cli
    namespace: openshift
  register: cli_img_info
 
- name: Create CronJob for AD sync
  k8s:
    state: present
    kind: CronJob
    api_version: batch/v1beta1
    name: ad-sync
    namespace: openshift-config
    merge_type:
      - strategic-merge
      - merge    
    definition:
      metadata:
        labels:
          run: ad-sync
      spec:
        schedule: '{{ ad_sync_cron_schedule }}'
        concurrencyPolicy: Replace
        suspend: false
        jobTemplate:
          metadata:
            creationTimestamp: null
          spec:
            template:
              metadata:
                creationTimestamp: null
                labels:
                  run: ad-sync
              spec:
                restartPolicy: OnFailure
                serviceAccountName: ad-sync
                containers:
                  - name: ad-sync
                    image: "{{cli_img_info.resources[0].spec.tags[0].from.name}}"
                    command:
                      - /bin/sh
                      - '-c'
                      - /ad-sync/ad-sync.sh
                    resources: {}
                    volumeMounts:
                      - name: ad-sync
                        mountPath: /ad-sync
                    terminationMessagePath: /dev/termination-log
                    terminationMessagePolicy: File
                    imagePullPolicy: Always
                serviceAccount: ad-sync
                volumes:
                  - name: ad-sync
                    configMap:
                      name: ad-sync
                      defaultMode: 347