---
- name: Create LDAP password secret
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: ldap-bind-password
        namespace: openshift-config
      data:
        bindPassword: "{{ ldap_bind_password }}"

- name: Create Config Map for LDAP root CA
  k8s:
    state: absent
    kind: ConfigMap
    name: ldap-root-ca
    namespace: openshift-config
    merge_type:
      - strategic-merge
      - merge
    definition:
      data:
        ca.crt: "{{ lookup('file', '{{ ldap_root_ca }}', rstrip=False) }}"


- name: Ensure OAuth provider is present
  k8s:
    api_version: v1
    state: present
    kind: OAuth
    name: cluster
    apply: yes
    definition:
      spec:
        identityProviders:
          - LDAP:
            name: LDAP
            type: LDAP
            mappingMethod: claim
            ldap:
              attributes:
                email:
                  - mail
                id:
                  - sAMAccountName
                name:
                  - displayName
                preferredUsername:
                  - sAMAccountName
              bindDN: 'cn=Zlinuxldapbind,ou=Applications,ou=TEST Users,dc=test,dc=co,dc=uk'
              bindPassword:
                name: ldap-bind-password
             # ca:
             #   name: ldap-root-ca
              insecure: true
              url: 'ldap://adserver/ou=TEST Users,dc=test,dc=co,dc=uk?sAMAccountName'
