---
# tasks file for openshift-olm

- name: Ensure default sources are disabled
  community.kubernetes.k8s:
    state: present
    kind: OperatorHub
    api_version: config.openshift.io/v1
    name: cluster
    merge_type:
      - strategic-merge
      - merge
    definition:
      spec:
        disableAllDefaultSources: true

- name: Ensure custom catalog presence
  community.kubernetes.k8s:
    state: present
    kind: CatalogSource
    api_version: operators.coreos.com/v1alpha1
    name: custom-operator-catalog
    namespace: openshift-marketplace
    merge_type:
      - strategic-merge
      - merge
    definition:
      spec:
        sourceType: grpc
        image: "{{ olm_image }}"
        displayName: Custom Operator Catalog
        publisher: TEST

- name: Ensure custom mirrors are present
  community.kubernetes.k8s:
    state: present
    kind: ImageContentSourcePolicy
    api_version: operator.openshift.io/v1alpha1
    name: redhat-operator-index
    merge_type:
      - strategic-merge
      - merge
    definition:
      spec:
        repositoryDigestMirrors:
        - mirrors:
          - quay.test.com:5001/olm-mirror/openshift4-ose-elasticsearch-proxy
          source: registry.redhat.io/openshift4/ose-elasticsearch-proxy
        - mirrors:
          - quay.test.com:5001/olm-mirror/openshift4-ose-logging-curator5
          source: registry.redhat.io/openshift4/ose-logging-curator5
        - mirrors:
          - quay.test.com:5001/olm-mirror/openshift4-ose-cluster-logging-operator-bundle
          source: registry.redhat.io/openshift4/ose-cluster-logging-operator-bundle
        - mirrors:
          - quay.test.com:5001/olm-mirror/openshift4-file-integrity-rhel8-operator-metadata
          source: registry.redhat.io/openshift4/file-integrity-rhel8-operator-metadata
        - mirrors:
          - quay.test.com:5001/olm-mirror/openshift4-ose-logging-elasticsearch6
          source: registry.redhat.io/openshift4/ose-logging-elasticsearch6
        - mirrors:
          - quay.test.com:5001/olm-mirror/openshift4-file-integrity-rhel8-operator
          source: registry.redhat.io/openshift4/file-integrity-rhel8-operator
        - mirrors:
          - quay.test.com:5001/olm-mirror/openshift4-ose-oauth-proxy
          source: registry.redhat.io/openshift4/ose-oauth-proxy
        - mirrors:
          - quay.test.com:5001/olm-mirror/openshift4-ose-logging-fluentd
          source: registry.redhat.io/openshift4/ose-logging-fluentd
        - mirrors:
          - quay.test.com:5001/olm-mirror/openshift4-ose-logging-kibana6
          source: registry.redhat.io/openshift4/ose-logging-kibana6
        - mirrors:
          - quay.test.com:5001/olm-mirror/openshift4-ose-cluster-logging-operator
          source: registry.redhat.io/openshift4/ose-cluster-logging-operator
        - mirrors:
          - quay.test.com:5001/olm-mirror/openshift4-ose-elasticsearch-operator
          source: registry.redhat.io/openshift4/ose-elasticsearch-operator
        - mirrors:
          - quay.test.com:5001/olm-mirror/openshift4-ose-elasticsearch-operator-bundle
          source: registry.redhat.io/openshift4/ose-elasticsearch-operator-bundle
