---
- name: Set Custom Console Banner name
  k8s:
    api_version: operator.openshift.io/v1
    state: present
    merge_type:
      - strategic-merge
      - merge
    kind: Console
    name: cluster
    definition:
      spec:
        customization:
          customProductName: "TEST POC"

- name: Set custom notification banner
  k8s:
    api_version: console.openshift.io/v1
    state: present
    merge_type:
      - strategic-merge
      - merge
    kind: ConsoleNotification
    definition:
      metadata:
        name: example
      spec:
        text: "TEST POC"
        location: BannerTop
        color: '#ffffff'
        backgroundColor: '#66b266'

- name: Customise the web console URL
  k8s:
    api_version: operator.openshift.io/v1
    state: present
    kind: Console
    merge_type:
      - strategic-merge
      - merge
    definition:
      metadata:
        name: cluster
      spec:
        route:
          hostname: "console.apps.{{ cluster_name }}.{{ domain }}"
