---
- name: Ensure bootstrap VM is present
  community.vmware.vmware_guest:
    hostname: "{{ vhost }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ vdatacenter }}"
    datastore: "{{ vdatastore }}"
    # If deploying to a single esxi host - use instead of datacenter
    # esxi_hostname: "{{ esxi_host }}"
    # guest_id: coreos64Guest
    cluster: "{{ vcluster}}"
    validate_certs: false
    name: "{{ item.hostname }}"
    folder: "{{ vm_folder }}"
    template: "{{ vm_template }}"
    hardware:
      memory_mb: "{{ vm_memory_mb[item.role] }}"
      num_cpus: "{{ vm_num_cpus[item.role] }}"
    # If setting specific network cards
    #networks:
    #  - name: "{{ vnetwork }}"
    #    device_type: vmxnet3
    disk:
      - size_gb:  "{{ vm_disk_size_gb[item.role] }}"
        datastore: "{{ vdatastore }}"
        autoselect_datastore: true
    state: poweredon
    vapp_properties:
      - id: guestinfo.ignition.config.data.encoding
        value: "base64"
      - id: guestinfo.ignition.config.data
        value: "{{ lookup('file', '{{ cluster_config_dir }}/ignitions/{{ item.hostname }}.ign') | b64encode }}"
    advanced_settings:
      - key: disk.EnableUUID
        value: "TRUE"
      - key: guestinfo.afterburn.initrd.network-kargs
        value: "ip={{ item.ip }}::{{ gateway }}:{{ netmask }}:{{ item.hostname }}.{{ domain }}:ens192:none nameserver={{ dns }}"
  delegate_to: localhost
  with_items: "{{ bootstrap }}"

- name: Ensure master VMs are present
  community.vmware.vmware_guest:
    hostname: "{{ vhost }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ vdatacenter }}"
    # esxi_hostname: "{{ esxi_host }}"
    cluster: "{{ vcluster}}"
    validate_certs: false
    name: "{{ item.hostname }}"
    folder: "{{ vm_folder }}"
    template: "{{ vm_template }}"
    hardware:
      memory_mb: "{{ vm_memory_mb[item.role] }}"
      num_cpus: "{{ vm_num_cpus[item.role] }}"
#    networks:
#      - name: "{{ vnetwork }}"
#        device_type: vmxnet3
    disk:
      - size_gb:  "{{ vm_disk_size_gb[item.role] }}"
        datastore: "{{ vdatastore}}"
        autoselect_datastore: true
    state: poweredon
    vapp_properties:
      - id: guestinfo.ignition.config.data.encoding
        value: "base64"
      - id: guestinfo.ignition.config.data
        #value: "{{ lookup('file', '{{ cluster_config_dir }}/master.ign') | b64encode }}"
        value: "{{ lookup('file', '{{ cluster_config_dir }}/ignitions/{{ item.hostname }}.ign') | b64encode }}"
    advanced_settings:
      - key: disk.EnableUUID
        value: "TRUE"
      - key: guestinfo.afterburn.initrd.network-kargs
        value: "ip={{ item.ip }}::{{ gateway }}:{{ netmask }}:{{item.hostname}}.{{ domain }}:ens192:none nameserver={{ dns }}"
  delegate_to: localhost
  with_items: "{{ nodes | selectattr('role','match','control') | list }}"
  when: item.role == "control"
  loop_control:
    pause: 20

- name: Wait for bootstrap to complete
  command: openshift-install --dir={{ cluster_config_dir }} wait-for bootstrap-complete --log-level debug
  register: result_bootstrap

- name: Ensure infra VMs are present
  community.vmware.vmware_guest:
    hostname: "{{ vhost }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ vdatacenter }}"
    # esxi_hostname: "{{ esxi_host }}"
    cluster: "{{ vcluster}}"
    validate_certs: false
    name: "{{ item.hostname }}"
    folder: "{{ vm_folder }}"
    template: "{{ vm_template }}"
    hardware:
      memory_mb: "{{ vm_memory_mb[item.role] }}"
      num_cpus: "{{ vm_num_cpus[item.role] }}"
   # networks:
   #   - name: "{{ vnetwork }}"
   #     device_type: vmxnet3
    disk:
      - size_gb:  "{{ vm_disk_size_gb[item.role] }}"
        datastore: "{{ vdatastore}}"
        autoselect_datastore: true
    state: poweredon
    vapp_properties:
      - id: guestinfo.ignition.config.data.encoding
        value: "base64"
      - id: guestinfo.ignition.config.data
        value: "{{ lookup('file', '{{ cluster_config_dir }}/ignitions/{{ item.hostname }}.ign') | b64encode }}"
    advanced_settings:
      - key: disk.EnableUUID
        value: "TRUE"
      - key: guestinfo.afterburn.initrd.network-kargs
        value: "ip={{ item.ip }}::{{ gateway }}:{{ netmask }}:{{item.hostname}}.{{ domain }}:ens192:none nameserver={{ dns }}"
  delegate_to: localhost
  with_items: "{{ nodes | selectattr('role','match','infra') | list }}"
  when: item.role == "infra"
  loop_control:
    pause: 20

- name: Wait for node-bootstraper csrs to approve
  shell: "oc get csr -o json --kubeconfig={{ cluster_config_dir }}/auth/kubeconfig | jq -r '.items[] | select(.status == {}) | .metadata.name'" # noqa 301 306
  register: result_csr
  until: result_csr['stdout_lines']|count == nodes |selectattr('role', 'equalto', 'infra')|list|length
  retries: 60
  delay: 60

- name: Approve the csrs
  command: "oc adm certificate approve {{ item }} --kubeconfig={{ cluster_config_dir }}/auth/kubeconfig" # noqa 301
  loop: "{{ result_csr['stdout_lines'] }}"

- name: Wait for system:node csrs to approve
  shell: "oc get csr -o json --kubeconfig={{ cluster_config_dir }}/auth/kubeconfig | jq -r '.items[] | select(.status == {}) | .metadata.name'"  # noqa 301 306
  register: result_system
  until: result_system['stdout_lines']|count == nodes |selectattr('role', 'equalto', 'infra')|list|length
  retries: 60
  delay: 60

- name: Approve the csrs
  command: "oc adm certificate approve {{ item }} --kubeconfig={{ cluster_config_dir }}/auth/kubeconfig" # noqa 301
  loop: "{{ result_system['stdout_lines'] }}"

- name: Wait for install complete
  command: openshift-install wait-for install-complete --dir={{ cluster_config_dir }} --log-level debug
  register: result_complete

- name: Output results from openshift-install wait-for install-complete
  debug:
    msg: "{{ result_complete.stderr | regex_findall('level=info.*') | list }}"

- name: Ensure httpd is stopped
  systemd:
    state: stopped
    name: httpd
  become: true
