---
- name: Configure cluster
  hosts: localhost
  vars_files:
    - ../vars/config.yml
    #- ../vars/vault
  module_defaults:
    community.kubernetes.k8s_info:
      validate_certs: false
      kubeconfig: "/home/n772072/openshift/provision_openshift/files/openshift/auth/kubeconfig"
      host: "https://api.{{ cluster_name }}.{{ domain }}:6443"
    community.kubernetes.k8s:
      validate_certs: false
      kubeconfig: "/home/n772072/openshift/provision_openshift/files/openshift/auth/kubeconfig"
      host: "https://api.{{ cluster_name }}.{{ domain }}:6443"
  roles:
    #- openshift-node-customisations #done
    #- openshift-storage #done
    #- openshift-image-registry #done
    #- openshift-etcd #done, fix pod name search/fetch
    #- openshift-infra-nodes #done
    #- openshift-identity #done
    #- openshift-rbac #done
    #- openshift-ingress
    #- openshift-certificates #done
    - openshift-olm #done but need to apply generated imagecontentsourcepolicy from mirroring - later
    #- openshift-custom-registries #done
    #- openshift-monitoring #done
    #- openshift-logging #issues with storage
    #- openshift-console #done
    - openshift-finalise #todo
