---
- name: Generate cluster ignition files
  hosts: localhost
  vars_files:
    - ../vars/config.yml
  roles:
    - openshift-preflight-checks
    - openshift-ignition

- name: Provision CoreOS nodes
  hosts: localhost
  vars_files:
    - ../vars/config.yml
 # Please keep credentials in a vault e.g.
 #   - ../vars/vault
  roles:
    - openshift-vms
    - openshift-infra-nodes
    - openshift-ingress
    - openshift-vms-compute
